### ISSUE TITLE
Running Logstash with Java 11 warns about deprecated use of `UseConcMarkSweepGC`

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#10495]
When running Logstash `6.7.0` Build Candidate with OpenJDK Java 11, a deprecation warning about the use of `UseConcMarkSweepGC` is displayed:

```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release. 
```

We should look at the options in `jvm.options` and supply suitable options for running in Java 11

**Comment by sastorsl** [comment]
This is still an issue in `logstash-7.10.0`

**Comment by MakoWish** [comment]
This issue is nearly three years old, and no traction? I am now on Logstash 7.16.2 and still getting the same warning.

**Comment by yaauie** [comment]
This issue has been addressed.

The flag is only provided to the Java executable when run on [Java 8-13](https://github.com/elastic/logstash/blob/v7.16.2/config/jvm.options#L20), and is not provided when run on a more modern Java where the flag is unavailable.

**Comment by MakoWish** [comment]
It does not seem to be addressed, as we are using the bundled JDK and still getting the warning with 7.16.2.

**Comment by yaauie** [comment]
It has been addressed:

 - Logstash 7.16.2 [bundles JDK 11.0.13](https://github.com/elastic/logstash/blob/v7.16.2/versions.yml#L7-L11)
 - Java 11 provides _and supports_ concurrent mark-and-sweep garbage collector with this flag, but warns that future versions of Java won't have it (it was removed in Java 14)
 - On Java 11, concurrent mark-and-sweep is the generally recommended sensible default garbage collector for Logstash's usage pattern.
 - Logstash _only_ provides the flag to Javas [between 8 and 13](https://github.com/elastic/logstash/blob/v7.16.2/config/jvm.options#L20) (inclusive) _where it is supported_.
 - When Logstash is run on Java 17, for example, the unsupported-on-java-17 flag is not provided.

The warning comes from Java, and can safely be ignored.
