### ISSUE TITLE
The 1.4.2 bin/plugin is not working due to version inconsistency

### ISSUE THREAD

**Issue by jamtur01** [elastic/logstash#2252]
I tried to do

    $ bin/plugin install contrib

It downloaded a 0 byte file.

logstash-contrib-1.4.2-modified.tar.gz

The file name was based on the string pulled from lib/logstash/version.rb which is:

    LOGSTASH_VERSION = "1.4.2-modified"

This needs to be:

    LOGSTASH_VERSION = "1.4.2"

The error is in the logstash_1.4.2-1-2c0f5a1_all packages.

**Comment by marksmithson** [comment]
Work around before running plugin install:
`sed -i 's/1.4.2-modified/1.4.2/g' /opt/logstash/lib/logstash/version.rb`

**Comment by jamtur01** [comment]
Any progress on this? It's still biting folks.

**Comment by miron9** [comment]
If you need the bin/plugin script to work now I would suggest just correcting one line in it that is responsible for determining the version - I fixed it on Centos 6 by running:

sed -i "s,'{print \$2}','{print \$2}'\|cut -d- -f1,g" /opt/logstash/bin/plugin

**Comment by jamtur01** [comment]
@miron9 That's okay if you don't mind sed an installed package. I'd much prefer it work out of the box so I don't need to custom tweak. 

@electrical / @jordansissel - 1.5.0 is still not out and this is still broken. Can we please fix it? Especially as not everyone is going to upgrade immediately.

**Comment by jamtur01** [comment]
Following up again - helped two more people fix this in the last week.

**Comment by electrical** [comment]
@jamtur01 i've made a copy of the package and added the -modified part to it.
can you still if this fixes it?

Cheers.

**Comment by jamtur01** [comment]
Now I get:

```bash
# bin/plugin install contrib
cp: cannot stat ‘/opt/logstash/vendor/logstash/logstash-contrib-1.4.2-modified/*’: No such file or directory
```

**Comment by electrical** [comment]
Ah. most likely because the path in the tarball is not correct.
Will try to fix that and re-upload a new tarball.

**Comment by suyograo** [comment]
```
suyog@machine:~/bin/releases/logstash-1.4.4$ bin/plugin install contrib
 HTTP/1.1 200 OK
  Accept-Ranges: bytes
...
suyog@machine:~/bin/releases/logstash-1.4.4$ ls -lrt ./vendor/logstash/logstash-contrib-1.4.4.tar.gz
-rw-r--r--  1 suyog  staff  48907558 Jul 21 11:26 ./vendor/logstash/logstash-contrib-1.4.4.tar.gz
````

**Comment by suyograo** [comment]
Fixed in 1.4.3 and 1.4.4.
