### ISSUE TITLE
Metrics filter does not work in Logstash 2.0 Beta / Elasticsearch 2.0 Beta

### ISSUE THREAD

**Issue by schmorgs** [elastic/logstash#3985]
Have this plugin configured in my Logstash filter section : 
```
  metrics {
    meter => "events" 
	add_field => [ "host", "localhost" ]
	add_field => [ "type", "indexer-metric" ]
  }
```

I have output plugins configured for Elasticsearch and stdout 

I can see the metric messages being generated every 5 seconds (stdout), but they never appear in Elasticsearch.

When I run in debug mode, I see that indexing the document is failing, with the reason looking like a dot in the field name is not allowed : 
```
:response=>{"create"=>{"_index"=>"logstash-indexer-metric-2015.10.02", "_type"=>"indexer-metric", "_id"=>"AVAn7w1sB8Lrfh7xNTcR", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"Field name [events.count] cannot contain '.'"}}}, :level=>:warn}
```

**Comment by jordansissel** [comment]
What version of Elasticsearch?

**Comment by schmorgs** [comment]
Elasticsearch 2.0.0-beta2
Logstash 2.0.0-beta1

**Comment by jordansissel** [comment]
Looks like a breaking change introduced in Elasticsearch 2.0 (https://github.com/elastic/elasticsearch/pull/12068). Recommend you file a ticket against the [metrics filter](github.com/logstash-plugins/logstash-filter-metrics/issues) and we can figure out what to do to resolve this.

**Comment by jordansissel** [comment]
(closing; let's move this discussion to https://github.com/logstash-plugins/logstash-filter-metrics/issues)

**Comment by suyograo** [comment]
Fixed in new metrics filter v 3.0.0

**Comment by IngaFeick** [comment]
I downloaded and installed the 3.0.0 version of the metrics filter today and the issue is not fixed for me. I cannot find anything in the documentation on how to check the version of an installed plugin. Do you guys have an idea on how to make sure that my 3.0.0 installation has really succeeded? 
Logstash version is 2.0.0
Thank you

**Comment by untergeek** [comment]
@IngaFeick 

```
/opt/logstash/bin/plugin list --verbose logstash-filter-metrics
logstash-filter-metrics (3.0.0)
```

**Comment by IngaFeick** [comment]
Awesome, thank you!
