### ISSUE TITLE
kafka input spinning on cpu

### ISSUE THREAD

**Issue by bobrik** [elastic/logstash#4078]
Trying 2.0.0-beta3, here's my config:

```
input {
  kafka {
    codec               => "json"
    topic_id            => "test"
    group_id            => "logstash"
    consumer_threads    => 4
    auto_offset_reset   => "largest"
    zk_connect          => "zk:2181"
  }
}

output {
  stdout {
    codec => "rubydebug"
  }

  file {
    path => "/var/log/logstash/%{program}/%{logsource}/%{+YYYY-MM-dd}.log"
    message_format => "%{@timestamp} [pid:%{pid}] %{message}"
  }
}
```

Debug mode logs after start up only show this:

```
log4j, [2015-10-22T15:10:06.826] DEBUG: org.apache.zookeeper.ClientCnxn: Got ping response for sessionid: 0x25040575d7cbaf7 after 185ms
log4j, [2015-10-22T15:10:08.829] DEBUG: org.apache.zookeeper.ClientCnxn: Got ping response for sessionid: 0x25040575d7cbaf7 after 186ms
log4j, [2015-10-22T15:10:10.834] DEBUG: org.apache.zookeeper.ClientCnxn: Got ping response for sessionid: 0x25040575d7cbaf7 after 187ms
log4j, [2015-10-22T15:10:12.837] DEBUG: org.apache.zookeeper.ClientCnxn: Got ping response for sessionid: 0x25040575d7cbaf7 after 184ms
log4j, [2015-10-22T15:10:14.840] DEBUG: org.apache.zookeeper.ClientCnxn: Got ping response for sessionid: 0x25040575d7cbaf7 after 183ms
log4j, [2015-10-22T15:10:16.844] DEBUG: org.apache.zookeeper.ClientCnxn: Got ping response for sessionid: 0x25040575d7cbaf7 after 184ms
log4j, [2015-10-22T15:10:18.847] DEBUG: org.apache.zookeeper.ClientCnxn: Got ping response for sessionid: 0x25040575d7cbaf7 after 183ms
log4j, [2015-10-22T15:10:20.850] DEBUG: org.apache.zookeeper.ClientCnxn: Got ping response for sessionid: 0x25040575d7cbaf7 after 183ms
log4j, [2015-10-22T15:10:22.851] DEBUG: org.apache.zookeeper.ClientCnxn: Got ping response for sessionid: 0x25040575d7cbaf7 after 184ms
```

Logstash consumes full CPU in idle more after start up, all in user mode. Messages from topics appear, there's no issue with it.

Haven't tried kafka input with earlier releases, could be an old issue.

**Comment by bobrik** [comment]
Tried 1.5.4, no issue there.

**Comment by boernd** [comment]
Hi, we have the same issue with logstash-2.0.0. The following thread seems responsible:

LWP:
```
1701  1733   29 logstash 99.9 Nov18    16:10:48 /opt/.../java/jdk1.8.0_60/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.io.tmpdir=/opt/.../logstash/logstash-2.0.0 -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintClassHistogram -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -Xloggc:./log/logstash-server-gc.log -Xmx500m -Xss2048k -Djffi.boot.library.path=/opt/.../logstash/logstash-2.0.0/vendor/jruby/lib/jni -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.io.tmpdir=/opt/.../logstash/logstash-2.0.0 -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintClassHistogram -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -Xloggc:./log/logstash-server-gc.log -Xbootclasspath/a:/opt/.../logstash/logstash-2.0.0/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/opt/.../logstash/logstash-2.0.0/vendor/jruby -Djruby.lib=/opt/.../logstash/logstash-2.0.0/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main --1.9 /opt/.../logstash/logstash-2.0.0/lib/bootstrap/environment.rb logstash/runner.rb agent -f /opt/.../logstash/logstash-2.0.0/config/server -l /opt/.../logstash/logstash-2.0.0/log/logstash-server.log
```

Thread:
```
"<kafka" #15 daemon prio=5 os_prio=0 tid=0x0000000000a94000 nid=0x6c5 runnable [0x00007f68490cb000]
   java.lang.Thread.State: RUNNABLE
	at org.jruby.ast.InstVarNode.getVariable(InstVarNode.java:105)
	at org.jruby.ast.InstVarNode.interpret(InstVarNode.java:101)
	at org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:60)
	at org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:60)
	at org.jruby.ast.IfNode.interpret(IfNode.java:110)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.WhileNode.interpret(WhileNode.java:131)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
	at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
	at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
	at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
	at org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
	at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
	at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
	at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
	at org.jruby.runtime.Block.call(Block.java:101)
	at org.jruby.RubyProc.call(RubyProc.java:290)
	at org.jruby.RubyProc.call(RubyProc.java:228)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
	at java.lang.Thread.run(Thread.java:745)
```

Whole threaddump attached.
[threaddump.txt](https://github.com/elastic/logstash/files/38803/threaddump.txt)

**Comment by bobrik** [comment]
Any progress on this one? We're stuck on 1.5.4 and it is kind of slow.

**Comment by prasincs** [comment]
I've been running into same issue for logstash 2.1

**Comment by yuankui** [comment]
Hi, we came across the same issue.

kafka thread conume too much cpu..

![image](https://cloud.githubusercontent.com/assets/236535/11775295/8b8a2202-a278-11e5-87ac-f7cc8dafb51b.png)

![image](https://cloud.githubusercontent.com/assets/236535/11775267/519ad532-a278-11e5-9978-15615452c5cd.png)

**Comment by suyograo** [comment]
Folks, we just fixed the issue. Can you upgrade to 2.0.3 of this plugin?

```
bin/plugin install --version 2.0.3 logstash-input-kafka
```

We'll do a LS release soon as soon as we verify this fixes it. Thanks!

**Comment by suyograo** [comment]
Closing in favor of https://github.com/logstash-plugins/logstash-input-kafka/issues/52. This has been fixed in v2.0.3, see my comment above for instructions to update to this version. We'll be releasing LS 2.1.1 soon with this fix.

**Comment by bobrik** [comment]
@suyograo I've tried 2.1.1, still seeing the issue. Looks like it comes with 2.0.1:

```
root@wat:/opt/logstash# ./bin/logstash --version
logstash 2.1.1

root@wat:/opt/logstash# ls ./vendor/bundle/jruby/1.9/gems | fgrep kafka
jruby-kafka-1.4.0-java
logstash-input-kafka-2.0.2
logstash-output-kafka-2.0.1
```

**Comment by danielzheng** [comment]
@suyograo Not fixed int 2.1.1 release.

**Comment by suyograo** [comment]
@danielzheng sorry I meant LS version 2.1.2 which will be released soon. Meanwhile, you can get this fix by `bin/plugin install --version 2.0.3 logstash-input-kafka`

**Comment by danielzheng** [comment]
I just found this commit https://github.com/logstash-plugins/logstash-input-kafka/commit/ca54a317c7cd9136ccbf8f3142d271c4a55ab67e and patched it into 2.1.1 release.
That works fine now.
