### ISSUE TITLE
Cannot replace field with value containing hash at the end

### ISSUE THREAD

**Issue by karolzmuda** [elastic/logstash#4195]
I'm using filter with following code:

if [to_addr] =~ "^\d{3}$" {
  mutate {
    replace => [ "to_addr", "*%{to_addr}#" ]
  }
}

What is expected:
input: [to_addr] = 123
output: [to_addr] = *123#

What is achieved:
input: [to_addr] = 123
output: [to_addr] = *123

If I add any sign in the filter replace method behind hash the hash sign and added sign are correctly visible in the field value (for example "%{to_addr}#0" works as expected)

If I use hard-coded number, for example:

if [to_addr] == "123" {
  mutate {
    replace => [ "to_addr", "*123#" ]
  }
}

Everything works as expected.
What's happening here? Thanks for help.

**Comment by ph** [comment]
Which version of logstash you are using? This bug was fixed in 1.5.4 by this PR https://github.com/elastic/logstash/pull/3937

https://github.com/elastic/logstash/blob/master/CHANGELOG.md#154-august-20-2015

**Comment by karolzmuda** [comment]
I am using Logstash 1.5.4, sorry for not mentioning that at the beginning. Unfortunately this issue is still present.

**Comment by ph** [comment]
Okay I can reproduce the issue on 1.5.4 but its fixed on 1.5.5 and 2.0, so the changelog is wrong :disappointed:  I will make a PR to fix the changelog.

```
input { stdin {}}
filter {
  if [message] =~ "^\d{3}$" {
    mutate {
      replace => [ "message", "*%{message}#" ]
    }
  }
}
output { stdout { codec => rubydebug } }
```
