### ISSUE TITLE
Master package build tasks fails to install last available version of logstash-input-beats

### ISSUE THREAD

**Issue by ruflin** [elastic/logstash#4887]
Running `logstash-plugin install logstash-input-beats` in the most recent snapshot leads to the following error:

```
Installing logstash-input-beats
Error Bundler::PathError, retrying 1/10
...
Error Bundler::PathError, retrying 10/10
The path `/opt/logstash/logstash-core-plugin-api` does not exist.
Too many retries, aborting, caused by Bundler::PathError
ERROR: Installation Aborted, message: The path `/opt/logstash/logstash-core-plugin-api` does not exist.
```

I tried running `logstash-plugin update` before. To my surprise I get the following question:

```
You are updating logstash-input-beats to a new version 2.2.2, which may not be compatible with 0.9.4. are you sure you want to proceed (Y/N)?
```

In the end the update fails with the same error as mentioned before.

Unrelated note: The extracted snapshot folder is called `logstash-3.0.0.dev` instead of `5.0.0`

**Comment by purbon** [comment]
re> `Unrelated note: The extracted snapshot folder is called logstash-3.0.0.dev instead of 5.0.0` version is still not raised in master, we might like to that soon, what do you think? @jsvd @suyograo

**Comment by purbon** [comment]
I confirm, building packages in master install the `0.9.4` beats version, while the last good one is `2.2.2`as @ruflin properly reported.

**Comment by purbon** [comment]
This error is due to conflicting version constraints for `concurrent-ruby`, while at core we required `1.0.0` forced, in the input beats >= `0.9.4` we have `~> 0.9.2`. In case of doubt see more into about the pessimistic operator at --> https://robots.thoughtbot.com/rubys-pessimistic-operator .

The input-beats is fixed by https://github.com/logstash-plugins/logstash-input-beats/pull/63

Will investigate also if this happen for more gems, being sure we install all recent versions for master is important.

**Comment by purbon** [comment]
I checked manually and the only _old_ / _stale_ dependency has been the `logstash-input-beats`, so if this gets fixed we are good to go, working on a test that can track this situation for master branch.

**Comment by purbon** [comment]
Fixed with the release of https://rubygems.org/gems/logstash-input-beats/versions/2.2.3, @ruflin can you validate this is not anymore a problem?

**Comment by ruflin** [comment]
@purbon What I did is taking the latest nigthly snapshot and tried our build. Unfortunately I still fails. I also tried to update the plugins on the snapshot which didn't help. See https://github.com/elastic/beats/pull/1240 Not sure if your changes are already part of the latest snapshot?

**Comment by purbon** [comment]
I tried with the `tgz` artifact, build out of master and I found #4907 that is actually fixed in #4908, after #4908 is merged I tested and it actually install the lastest version of input-beats without issues.

#4907 is actually the reason why your last test failed. 

/cc @tsg

**Comment by tsg** [comment]
Confirmed to be working, thanks a lot!
