### ISSUE TITLE
Invalid date makes logstash crash

### ISSUE THREAD

**Issue by martinhynar** [elastic/logstash#4989]
Hi,

I am running logstash 1.5.3 with output to elasticsearch and logstash crashes on invalid date format - `{"@timestamp":"2016-04-01T024752.995-0700"}` - missing colons in time.

I am getting this error:
```
NoMethodError: undefined method `tv_sec' for "2016-04-01T024752.995-0700":String
       evaluate at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/string_interpolation.rb:134
       evaluate at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/string_interpolation.rb:79
        collect at org/jruby/RubyArray.java:2407
       evaluate at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/string_interpolation.rb:79
       evaluate at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/string_interpolation.rb:26
        sprintf at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/event.rb:222
        receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-1.0.5-java/lib/logstash/outputs/elasticsearch.rb:504
         handle at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/outputs/base.rb:88
    output_func at (eval):1755
   outputworker at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:244
  start_outputs at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:166
```

I understood that there should be improved handling of invalid inputs to avoid complete crash based on #1240 and #1250 but seems that some cases were missed.

**Comment by jsvd** [comment]
can you show your full configuration? from the stack trace it's hard to understand what event caused this and how it was created

**Comment by martinhynar** [comment]
Sure,

```
input {
  courier {
    port => 1987
    transport => "tcp"
  }
}
output {
    elasticsearch {
      protocol => "node"
      cluster => "es-cluster"
      action => "index"
      codec => "json"
      node_name => "indexer"
      host => 'es...'
      port => 9300
      index => "logs-%{+YYYY-MM-dd}"
      manage_template => false
      workers => 1
    }
}
```

I am handing logs that are created as json lines via LS to ES. The timestamp in the input file is written by Java's date formatter with format "yyyy-MM-dd'T'HHmmss.SSS'Z'".

**Comment by jsvd** [comment]
which version of the input courier plugin are you using?

**Comment by martinhynar** [comment]
It is log-courier 1.6

**Comment by jsvd** [comment]
sorry, I meant the logstash plugin version for the courier input. you can find with `bin/plugin list --verbose`

**Comment by martinhynar** [comment]
it is the logstash courier plugin version

**Comment by jsvd** [comment]
I'm not sure how the event got created with such an internal structure.
in the place where it crashes, logstash is doing `event.sprintf("logs-%{+YYYY-MM-dd}")`

which works for a normally created event:

```
1.9 :007 > LogStash::Event.new.sprintf("logs-%{+YYYY-MM-dd}")
 => "logs-2016-04-04" 
```

giving it the malformed timestamp does not work well but does not crash, because the parsing of @timestamp fails and the current timestamp is used instead:

```
1.9 :010 > LogStash::Event.new("@timestamp" => "2016-04-01T024752.995-0700").sprintf("logs-%{+YYYY-MM-dd}")
 => "logs-2016-04-04" 
1.9 :011 > LogStash::Event.new("@timestamp" => "2016-04-01T024752.995-0700")["tags"]
 => ["_timestampparsefailure"] 
1.9 :012 > LogStash::Event.new("@timestamp" => "2016-04-01T024752.995-0700")["@timestamp"]
 => "2016-04-04T09:43:25.793Z" 
```

@driskell any idea on how this logstash event is being created so that the @timestamp is "corrupt"? it seems to be skipping the usual validation

**Comment by driskell** [comment]
The courier input doesn't define `@timestamp`.

@martinhynar :

> I am handing logs that are created as json lines via LS to ES. The timestamp in the input file is written by Java's date formatter with format "yyyy-MM-dd'T'HHmmss.SSS'Z'".

The @timestamp looks to be coming from the original JSON file being read - the colons are missing there. So looks like the logging application isn't logging with colons, then it works it's way through to Logstash and it can't parse the timestamp. Might need a filter setup in there to capture the _timestampparsefailure tag and remove it and then attempt apply a date filter that works on timestamps without a colon - looking at Logstash the original timestamp is kept in `_@timestamp` I think.

**Comment by jsvd** [comment]
thanks for the input @driskell 
what I'm failing to grasp is where, in logstash, is a json payload being transformed into a Logstash::Event so that the event is created with a broken `@timestamp`, which throws the exception later in the output when `event.sprintf` happens.

From the [configuration posted](https://github.com/elastic/logstash/issues/4989#issuecomment-205198816) the only input is courier, hence my confusion

**Comment by martinhynar** [comment]
From my perspective, log-courier is completely outside. It's role here is only to read log file and pass it to logstash. Same with courier plugin that just takes what comes in. 

One bit of information from me that I forgot to mention. There is `filter { json { source => "message", remove_field => ["message", "path", "offset"] } }` in between.

I tried to reproduce the problem without log-courier to find out minimal cofiguration. I ended up with:

```
input { file { path => "/tmp/in" } }
filter { json { source => "message" } }
output { elasticsearch { ...,  index => "logs-%{+YYYY-MM-dd}" } }
```

The index part is crucial. When there's  `%{+YYYY-MM-dd}"` LogStash crashes. If it is omitted and fixed name is used, event is stored with `_jsonparsefailure` added to `tags`.

I would expect logstash to drop such event and log it into own error log instead of dying.

**Comment by martinhynar** [comment]
Forgot to add, with the configuration from my latest post, `echo '{ "@timestamp": "2016-04-04T005525.440-0700"}' >> /tmp/in` crashes logstash.

**Comment by driskell** [comment]
@jsvd it happens when creating an event.

If `@timestamp` is part of the Hash passed into `Logstash::Event.new`, it uses it as the timestamp, but it will convert it into a `Logstash::Timestamp`. If that conversion fails it adds on the tag. See `init_timestamp` (search the logstash repository and you'll find it).

Though reading back here - I don't even think that is related.

@martinhynar can you provide an example line from the log file? My guess is the log file is logging in JSON with a `@timestamp` field. And I wonder if the json filter actually just overwrites the `@timestamp` field of the `Logstash::Event` rather than converting it into a `Logstash::Timestamp` first - thus you end up once at a point in `elasticsearch` output where it's trying to call a method of `Logstash::Timestamp` on a string, since `@timestamp` is now a string.

**Comment by driskell** [comment]
What version of `logstash-filter-json` codec?

**Comment by jsvd** [comment]
thank you for your time @martinhynar and @driskell 
this was fixed in version 1.0.1 of the filter-json. the bug was that even in the case of a decode failure (that envolves parsing the `@timestamp` when present, the event would be modified and therefore `@timestamp` would become a string.

```
joaoduarte@Joaos-MBP /tmp/logstash-1.5.3 % bin/plugin list --verbose filter-json
logstash-filter-json (1.0.0)
joaoduarte@Joaos-MBP /tmp/logstash-1.5.3 % echo '{"@timestamp": "07/sep/2015:07:50:54 UTC" }}' | bin/logstash -e 'input { stdin { } } filter { json { source => "message"} } output { stdout { codec => rubydebug } }'
Logstash startup completed
Trouble parsing json {:source=>"message", :raw=>"{\"@timestamp\": \"07/sep/2015:07:50:54 UTC\" }}", :exception=>#<LogStash::TimestampParserError: invalid timestamp string "07/sep/2015:07:50:54 UTC", error=java.lang.IllegalArgumentException: Invalid format: "07/sep/2015:07:50:54 UTC" is malformed at "/sep/2015:07:50:54 UTC">, :level=>:warn}
{
       "message" => "{\"@timestamp\": \"07/sep/2015:07:50:54 UTC\" }}",
      "@version" => "1",
    "@timestamp" => "07/sep/2015:07:50:54 UTC",
          "host" => "Joaos-MBP.lan",
          "tags" => [
        [0] "_jsonparsefailure"
    ]
}
Logstash shutdown completed
joaoduarte@Joaos-MBP /tmp/logstash-1.5.3 % cd ../logstash-1.5.6
joaoduarte@Joaos-MBP /tmp/logstash-1.5.6 % bin/plugin list --verbose filter-json
logstash-filter-json (1.0.1)
joaoduarte@Joaos-MBP /tmp/logstash-1.5.6 % echo '{"@timestamp": "07/sep/2015:07:50:54 UTC" }}' | bin/logstash -e 'input { stdin { } } filter { json { source => "message"} } output { stdout { codec => rubydebug } }'
Logstash startup completed
Trouble parsing json {:source=>"message", :raw=>"{\"@timestamp\": \"07/sep/2015:07:50:54 UTC\" }}", :exception=>#<LogStash::Json::ParserError: Unexpected close marker '}': expected ']' (for ROOT starting at [Source: [B@304cb930; line: 1, column: 0])
 at [Source: [B@304cb930; line: 1, column: 45]>, :level=>:warn}
{
       "message" => "{\"@timestamp\": \"07/sep/2015:07:50:54 UTC\" }}",
      "@version" => "1",
    "@timestamp" => "2016-04-04T11:47:25.510Z",
          "host" => "Joaos-MBP.lan",
          "tags" => [
        [0] "_jsonparsefailure"
    ]
}
```

more on this bug in https://github.com/logstash-plugins/logstash-filter-json/issues/14

**Comment by jsvd** [comment]
this no longer happens since 1.0.1, please upgrade to the most recent version of logstash-filter-json to avoid the issue

**Comment by martinhynar** [comment]
Just updated json-filter to 1.0.1 and with the above configuration and event being `{ "@timestamp": "2016-04-04T005525.440-0700"}` logstash still crashes.

**Comment by jsvd** [comment]
@martinhynar confirmed. https://github.com/logstash-plugins/logstash-filter-json/commit/d8222360d9baa85d23ecfb1c79eb5077481f2619 fixed this for 2.0.3 but there is no fix in 1.x

```
/tmp/logstash-1.5.6 % bin/logstash -f ../logstash-1.5.3/config
Logstash startup completed
{ "@timestamp": "2016-04-04T005525.440-0700"}
\Trouble parsing json {:source=>"message", :raw=>"{ \"@timestamp\": \"2016-04-04T005525.440-0700\"}", :exception=>#<LogStash::TimestampParserError: invalid timestamp string "2016-04-04T005525.440-0700", error=java.lang.IllegalArgumentException: Invalid format: "2016-04-04T005525.440-0700" is malformed at "5525.440-0700">, :level=>:warn}
{
       "message" => "{ \"@timestamp\": \"2016-04-04T005525.440-0700\"}",
      "@version" => "1",
    "@timestamp" => "2016-04-04T005525.440-0700",
          "host" => "Joaos-MBP.lan",
          "tags" => [
        [0] "_jsonparsefailure"
    ]
}
NoMethodError: undefined method `tv_sec' for "2016-04-04T005525.440-0700":String
       evaluate at /tmp/logstash-1.5.6/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.6-java/lib/logstash/string_interpolation.rb:135
       evaluate at /tmp/logstash-1.5.6/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.6-java/lib/logstash/string_interpolation.rb:80
        collect at org/jruby/RubyArray.java:2409
       evaluate at /tmp/logstash-1.5.6/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.6-java/lib/logstash/string_interpolation.rb:80
       evaluate at /tmp/logstash-1.5.6/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.6-java/lib/logstash/string_interpolation.rb:27
        sprintf at /tmp/logstash-1.5.6/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.6-java/lib/logstash/event.rb:222
         encode at /tmp/logstash-1.5.6/vendor/bundle/jruby/1.9/gems/logstash-codec-plain-1.0.0/lib/logstash/codecs/plain.rb:41
        receive at /tmp/logstash-1.5.6/vendor/bundle/jruby/1.9/gems/logstash-output-stdout-1.1.0/lib/logstash/outputs/stdout.rb:57
         handle at /tmp/logstash-1.5.6/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.6-java/lib/logstash/outputs/base.rb:88
    output_func at (eval):52
   outputworker at /tmp/logstash-1.5.6/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.6-java/lib/logstash/pipeline.rb:244
  start_outputs at /tmp/logstash-1.5.6/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.6-java/lib/logstash/pipeline.rb:166
bin/logstash -f ../logstash-1.5.3/config  17.01s user 0.80s system 176% cpu 10.105 total
1 joaoduarte@Joaos-MBP /tmp/logstash-1.5.6 % cd ..
joaoduarte@Joaos-MBP /tmp % cd logstash-2.2.3
joaoduarte@Joaos-MBP /tmp/logstash-2.2.3 % bin/logstash -f ../logstash-1.5.3/config
Settings: Default pipeline workers: 4
Logstash startup completed
{ "@timestamp": "2016-04-04T005525.440-0700"} 
Unrecognized @timestamp value, setting current time to @timestamp, original in _@timestamp field {:value=>"\"2016-04-04T005525.440-0700\"", :level=>:warn}
{
        "message" => "{ \"@timestamp\": \"2016-04-04T005525.440-0700\"}",
       "@version" => "1",
     "@timestamp" => "2016-04-04T12:52:38.829Z",
           "host" => "Joaos-MBP.lan",
           "tags" => [
        [0] "_timestampparsefailure"
    ],
    "_@timestamp" => "2016-04-04T005525.440-0700"
}
```

**Comment by suyograo** [comment]
Closing because this is a fixed issue
