### ISSUE TITLE
Security issue in the Debian package init script

### ISSUE THREAD

**Issue by interone-ms** [elastic/logstash#7726]
- Version: 1:5.5.0-1
- Operating System: Debian Jessie
- Steps to Reproduce:

1. Install logstash
2. Start it
3. Have your /var/log directory borked

The init script supplied by the Debian package contains these lines as part of the startup process (58-61): 

    # Ensure the log directory is setup correctly.
    [ ! -d "/var/log" ] && mkdir "/var/log"
    chown "$user":"$group" "/var/log"
    chmod 755 "/var/log"

This:

- breaks /var/log permissions by assigning uid/gid logstash:logstash
- does not make any sense at all, given that the logstash binary is started in a chroot, but the logfiles  /var/log/logstash-stdout.log and /var/log/logstash-stderr.log belong to root because they're created outside the chroot in line 73:

    $ ls -lah /var/log|grep logst
    drwxr-xr-x 15 logstash      logstash      4.0K Jul 18 06:25 .
    drwxrwxr-x  2 logstash      root          4.0K Jul 18 18:01 logstash
    -rw-r--r--  1 root          root           240 Jul 18 18:01 logstash-stderr.log
    -rw-r--r--  1 root          root           182 Jul 18 18:01 logstash-stdout.log

Also, I would classify this as a *security issue* because the /var/log directory becomes writable by logstash user.

**Comment by andrewvc** [comment]
I believe this is the correct fix https://github.com/jordansissel/pleaserun/pull/128

Thanks for reporting!

To clarify this *only* affects users using SysV init. Systemd, the current default in Debian, Ubuntu, and many other distros, is not affected.

**Comment by interone-ms** [comment]
There are people with a healthy dislike for systemd, like me ;) Thanks for the quick reaction!

**Comment by interone-ms** [comment]
@andrewvc I looked at your change - I believe it's not sufficient, there will be a change needed in logstash as well which sets `log_directory` to /var/log/logstash.

**Comment by andrewvc** [comment]
@interone-ms that's a good point, we'll also need to pass a different arg in for the log directory. I'll consult with @jordansissel or @untergeek on that since they know more about please run. I think we'll want the pleaserun change anyway as a safeguard.

**Comment by andrewvc** [comment]
@suyograo since you're taking over this one, you'll need these instructions to replace systemd with sysvinit on debian: http://without-systemd.org/wiki/index.php/How_to_remove_systemd_from_a_Debian_jessie/sid_installation

**Comment by jordansissel** [comment]
I think this is resolved with #7932

**Comment by andrewvc** [comment]
@jordansissel I'm reopening this since the pleaserun issue doesn't really fix this, we also need to pass in the correct arg for the log directory, not just `/var/log`

**Comment by andrewvc** [comment]
@suyograo are you still on this one, or should I take it?

**Comment by suyograo** [comment]
@andrewvc I've assigned this to @untergeek who's worked in this area before

**Comment by andrewvc** [comment]
@untergeek to clarify, the remaining work is to make the sysvinit script correctly log to /var/log/logstash instead of /var/log as it currently does

**Comment by untergeek** [comment]
@andrewvc, are you suggesting we change this?
```
  # Ensure the log directory is setup correctly.
  if [ ! -d "/var/log" ]; then
    mkdir "/var/log"
    chown "$user":"$group" "/var/log"
    chmod 755 "/var/log"
  fi


  # Setup any environmental stuff beforehand
  ulimit -n ${limit_open_files}

  # Run the program!
  nice -n "$nice" \
  chroot --userspec "$user":"$group" "$chroot" sh -c "
    ulimit -n ${limit_open_files}
    cd \"$chdir\"
    exec \"$program\" $args
  " >> /var/log/logstash-stdout.log 2>> /var/log/logstash-stderr.log &
```
In order for us to change this, we would have to do some extra work in the `system-install` script to change these values after the init script is installed.  This is because `path.logs` is set in the `logstash.yml`, which is not read by the `system-install` script, and is therefore not passed to `pleaserun`.

I'm not sure this is a terrific idea, to be honest, but I'm open to making an attempt.

**Comment by untergeek** [comment]
Because `logstash.yml` can be edited and changed independent of the `init` script, I'm a bit wary of tying these together in that way.

**Comment by untergeek** [comment]
After speaking with @andrewvc, we've decided that the security issue is solved, and we're going to leave the init script alone.  It will continue to log to `/var/log`, as presently constituted.

**Comment by jordansissel** [comment]
@untergeek @andrewvc +1. In terms of specifics, here is what I think:

* Pleaserun tries to give a consistent way to capture stdout and stderr to log files
* Logstash uses log4j2 and only writes logs to stdout as a convenience measure when run by a human from the terminal
* In Logstash, when running as a service, stdout/stderr are intended to capture errors that occur before log4j2 is initialized (jvm failures, etc).

For these reasons, I am +1 on what y'all came up with (leave the pleaserun log path alone).
