### ISSUE TITLE
LogStash::Pipeline Periodic Flush flush periodically

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#7754]
Failure in master: https://travis-ci.org/elastic/logstash/jobs/255692876#L8359-L8377

```
  1) LogStash::Pipeline Periodic Flush flush periodically
     Failure/Error: end.to be_falsey
     
       expected: falsey value
            got: true
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:13:in `block in handle_matcher'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:10:in `block in handle_matcher'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:9:in `handle_matcher'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `block in to'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `block in with_wait'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:28:in `with_wait'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `with_wait'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `to'
     # ./logstash-core/spec/logstash/pipeline_spec.rb:634:in `block in (root)'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /home/travis/build/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
     # ./lib/bootstrap/rspec.rb:13:in `<main>'
Finished in 7 minutes 11 seconds (files took 16.07 seconds to load)
2928 examples, 1 failure, 3 pending
Failed examples:
rspec ./logstash-core/spec/logstash/pipeline_spec.rb:626 # LogStash::Pipeline Periodic Flush flush periodically
Randomized with seed 37761
```

**Comment by jakelandis** [comment]
Closing this as fixed by https://github.com/elastic/logstash/commit/f1361de66023e539436c75299c58887873ee772a

I _think_ that adding the retry logic should allow this test to succeed.

**Comment by original-brownbear** [comment]
This is actually caused by https://github.com/elastic/logstash/commit/cf2ac9f927dd01c4ed801f601fe6a2317bc7bb24 and still fails for me locally and on Travis at times still. The problem is probably not relevant for production (I think no one has dummy filters and handles everthing via the `flush` calls??? :D ), but it's this:

We only call 

```rb
 flush_filters_to_batch(batch, :final => false) if signal.flush?
```
when we already have events in our `batch`. The test uses an input that doesn't generate events though, so we never call the periodic flush logic, only the lower part of `worker_loop` in the pipeline eventually calls this as a shutdown flush.
Since the pipeline quits right after it's started (because there's no events incoming?) this is not guaranteed to work out within the flush interval.
That said ... even the version before the change linked above shouldn't be 100% stable, just more likely for it to work properly.

**Comment by original-brownbear** [comment]
Fixed in #7863
