### ISSUE TITLE
Event stats inconsisent between Java and ruby execution 

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#8753]
Similar, but not identical to #8752 

Running a pipeline with a filter that adds events, the event stats are inconsistent when running logstash with `pipeline.java_execution` set to `true` or `false`:

Run a few events through the following pipeline: 

```
bin/logstash -e 'input { stdin { type => 'type1' } } filter { clone { clones => ["type1"] } } output { stdout { } }'
```

### ```pipeline.java_execution: true```

```
$ curl -s -XGET 'localhost:9600/_node/stats' | jq "{events: .events}" 
{
  "events": {
    "in": 2,
    "filtered": 2,
    "out": 2,
    "duration_in_millis": 50,
    "queue_push_duration_in_millis": 4
  }
}
```

### ```pipeline.java_execution: true```

```
$ curl -s -XGET 'localhost:9600/_node/stats' | jq "{events: .events}" 
{
  "events": {
    "in": 2,
    "filtered": 4,
    "out": 4,
    "duration_in_millis": 154,
    "queue_push_duration_in_millis": 5
  }
}
```

**Comment by andrewvc** [comment]
Any thoughts on this @original-brownbear ?

**Comment by original-brownbear** [comment]
@andrewvc yea, I think I could reproduce this just now (and know where it's coming from). The issue has a type, the wrong version (the upper one, has `true` and the lower one should have `false`, right @robbavey )

**Comment by original-brownbear** [comment]
@andrewvc we (or whoever is fluent in the current state of and plan for the metrics re-implementation) can look into this later if you like, there' s def. a bug in the Java exec here, but I think we should resolve this on the metric level not (as it currently is implemented) on the execution level.
We are getting the correct numbers from each individual filter and output delegator, these numbers should be the aggregates of those metric values and not the result of another redundant counter.
This wasn't a big problem in the past, but keeping this kind of counter straight with code gen isn't worth it since we correctly calculate that same information elsewhere already.

**Comment by w4** [comment]
This bug still seems to exist:

![image](https://user-images.githubusercontent.com/5258114/50920986-cc528a00-143e-11e9-9f4b-d23e8839c620.png)
