### ISSUE TITLE
Test Failure: LogStash::JavaPipeline Periodic Flush flush periodically

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#9180]
https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob--ruby-unit-tests/5/console

```
15:01:48     Failures:
15:01:48 
15:01:48       1) LogStash::JavaPipeline Periodic Flush flush periodically
15:01:48          Failure/Error:
15:01:48            wait(10).for do
15:01:48              # give us a bit of time to flush the events
15:01:48              output.events.empty?
15:01:48            end.to be_falsey
15:01:48          
15:01:48            expected: falsey value
15:01:48                 got: true
15:01:48          # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:13:in `block in handle_matcher'
15:01:48          # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:10:in `block in handle_matcher'
15:01:48          # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:9:in `handle_matcher'
15:01:48          # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `block in to'
15:01:48          # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `block in with_wait'
15:01:48          # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:28:in `with_wait'
15:01:48          # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `with_wait'
15:01:48          # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `to'
15:01:48          # ./logstash-core/spec/logstash/java_pipeline_spec.rb:631:in `block in (root)'
15:01:48          # ./vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:79:in `block in try'
15:01:48          # ./vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:95:in `block in try'
15:01:48          # ./vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:91:in `try'
15:01:48          # ./vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:123:in `try'
15:01:48          # ./logstash-core/spec/logstash/java_pipeline_spec.rb:630:in `block in (root)'
15:01:48          # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
15:01:48          # ./lib/bootstrap/rspec.rb:13:in `<main>'
15:01:48 
15:01:48     Finished in 6 minutes 53 seconds (files took 11.13 seconds to load)
15:01:48     3097 examples, 1 failure, 4 pending
15:01:48 
15:01:48     Failed examples:
15:01:48 
15:01:48     rspec ./logstash-core/spec/logstash/java_pipeline_spec.rb:623 # LogStash::JavaPipeline Periodic Flush flush periodically
15:01:48 
15:01:48     Randomized with seed 11395
```

This flush test failure might be related to latest change in the worker look flush handling? https://github.com/elastic/logstash/commit/0b83d4fc8683092e0174e39a6383626164604b1a
 @danhermann  ?

**Comment by original-brownbear** [comment]
Fixed in #9189 :)

**Comment by colinsurprenant** [comment]
still failing per  https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-unix-compatibility/os=amazon/5/console

**Comment by original-brownbear** [comment]
missed a spot there, should be good now via https://github.com/elastic/logstash/pull/9190 :)
